default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: photogram_dev

test:
  <<: *default
  database: photogram_test

production:
  <<: *default
  database: photogram
