# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aedc0bf9e14cc0be84a9f582e5683cc3800521cfde6cf6f09559666c20b369a4456d93a7d0036528c3199c2b70450e3eeb98e0c9971141954190d7615d46a47

test:
  secret_key_base: 4091e864ea63d6a3d0283384dbc29beaedb54c6cc6411957e24d56f6d442de11e82db3ca0677588eb1aff41d449980317dc740d82385ba503a9dca6c771b55cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
